ashley-brown13/ShowMe

db/migrations/20210308190840-create-user.js
db/models/user.js
views/layout.pug
views/user-register.pug
views/utils.pug

Finished user registration form.

Created user registration form

---

app.js
package-lock.json
package.json
routes/users.js
routes/validators.js
views/user-login.pug
views/user-signup.pug
views/utils.pug

Working on users/login.

---

db/migrations/20210309162716-create-show.js
db/models/show.js

created show table

---

db/migrations/20210309170409-create-rating.js
db/models/rating.js
db/models/show.js
db/models/user.js

Shows migration

---

db/migrations/20210309173619-create-review.js
db/models/review.js
db/models/show.js
db/models/user.js

Review table

---

db/models/show.js
db/models/showshelf.js
routes/shows.js
routes/users.js
views/layout.pug

Fixed error with belongsToMany in shows table.

---

routes/index.js
views/index.pug

Working on index page

---

routes/index.js

Sorry pull one more time

---

app.js
public/javascripts/show.js
routes/api/shows.js
routes/shows.js
views/show.pug

Figured out the delete buttongit add .!

---

public/javascripts/index.js
routes/index.js
views/index.pug

Working on front end of homepage

Working on front end of homepage

---

db/models/review.js
public/javascripts/delete-on-review.js
public/javascripts/show.js
routes/api/shows.js
views/reviews.pug
views/show.pug

Working in update button.

---

public/javascripts/delete-on-review.js
routes/shows.js
routes/validators.js
views/create-review.pug
views/reviews.pug
views/show.pug

Finished with the comment creation, editing, and deleting for logged in users.

Reviews 1.0 are finished

---

routes/shows.js
views/create-review.pug
views/reviews.pug

Fixed some bugs

---

routes/showShelves.js
views/showShelves.pug

Finished delete button on show shelves

finished delete shelf button

---

views/index.pug

Fixed indentation on main page

fixed indentation issue

---

public/javascripts/show.js
routes/shows.js
views/show.pug

Added "Add to Shelf" button on show page.

Added add to show shelves button on show page

---

routes/users.js
views/user-login.pug
views/user-signup.pug

Added a demo user button to the login and signup pages

Demo user added to login and signup

---

public/stylesheets/index.css
routes/index.js
views/index.pug

Styling on index page

---

views/index.pug

Deleted duplicated lines in pug index file.

Deleted duplicated lines in pug file

---

routes/index.js

Shows are now randomly selected.

Shows are now randomly selected.

---

public/stylesheets/showshelf.css

Configured showshelf page.

---

public/stylesheets/user-login.css
views/user-login.pug
views/utils.pug

Finished styling login page

---

views/index.pug

Made image a clickable link

---

views/user-login.pug

Fixed demo user login on login page

Fixed demo user login on login page

---

public/javascripts/show.js
views/showShelves.pug

Fixed addeventlistener bug.

---

app.js
auth.js
public/javascripts/show.js
routes/index.js

Removed the console.log()

---

views/index.pug

Removed title

---

routes/showShelves.js

Enabled ability to delete a show shelf

Enabled ability to delete a show shelf

---

public/javascripts/index.js

Added alert to show shelf

---

views/search.pug

Styled search page

---

README.md

Added the first three bullet points.

Added to ReadMe

---

public/javascripts/index.js
public/stylesheets/index.css
views/index.pug

Added disappearing  text when show added to showshelf

Added disappearing  text when show added to showshelf

---

README.md

Added my challenges to README
